name = "d1-cf-basic"
main = "src/index.js"
compatibility_date = "2023-10-30"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "MY_DATABASE"    # i.e. available in the Worker on env.MY_DATABASE
database_name = "d1-cf-basic"
database_id = "f2ff4931-2e3e-42d2-87b8-e5699f101e9b"
